# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181012_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
